services:

  movietopia-nginx:
    build: docker/nginx
    container_name: movietopia-nginx
    ports:
      - 5500:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/var/www/html
      # Mount config for development
      - ./docker/nginx:/etc/nginx/conf.d:cached
    links:
      - movietopia-php-fpm
    depends_on:
      - movietopia-php-fpm
      - movietopia-db
    networks:
      - movietopia

  movietopia-php-fpm:
    build: docker/php-fpm
    container_name: movietopia-php
    extra_hosts:
        - host.docker.internal:host-gateway
    volumes:
      - ./:/var/www/html:cached
    environment:
      PHP_IDE_CONFIG: serverName=Movietopia
    links:
      - movietopia-db
      - movietopia-db-test
      - movietopia-redis
    depends_on:
      - movietopia-db
      - movietopia-db-test
      - maildev
    networks:
      - movietopia
  movietopia-php-cli:
      build: docker/php-cli
      container_name: movietopia-php-cli
      extra_hosts:
          - host.docker.internal:host-gateway
      volumes:
          - ./:/var/www/html
          - composer:/root/.composer/cache
      environment:
          PHP_IDE_CONFIG: serverName=Movietopia
      links:
          - movietopia-db
          - movietopia-redis
      depends_on:
          - movietopia-db
          - maildev
      networks:
          - movietopia

  movietopia-db:
    build: docker/psql
    ports:
      - 11:5432
    container_name: movietopia-db
    volumes:
      - ./docker/psql/db-cache:/var/lib/postgresql
    environment:
      - POSTGRES_DB=movietopia
      - POSTGRES_USER=dev_movietopia
      - POSTGRES_PASSWORD=movietopia
    networks:
      - movietopia

  movietopia-db-test:
    build: docker/psql
    ports:
      - 12:5432
    container_name: movietopia-db-test
    volumes:
      - ./docker/psql/db-cache:/var/lib/postgresql
    environment:
      - POSTGRES_DB=movietopia
      - POSTGRES_USER=dev_movietopia
      - POSTGRES_PASSWORD=movietopia
    networks:
      - movietopia

  movietopia-redis:
    image: redis:7.4-alpine
    container_name: movietopia-redis
    volumes:
      - ./:/var/www/html:cached
    command: redis-server --requirepass secret
    networks:
      - movietopia


  movietopia-node:
    image: node:23.5-alpine
    container_name: movietopia-node
    volumes:
      - ./:/var/www/html/
    tty: true
    working_dir: /var/www/html/
    networks:
      - movietopia

  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "25:25"
    networks:
      - movietopia

volumes:
    logistics-db:
    logistics-redis:
    composer:

networks:
  movietopia:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.204.0/28
